### ISSUE TITLE
Add `console` interfaces

### ISSUE THREAD

**Issue by blakeembrey** [typed-typings/env-node#1]
Something I've always wanted to do. When writing node programs I really want to disable the default library and just use `lib.core.d.ts` to avoid bugs that occur from including all of `lib.d.ts`. However, this isn't possible with the current definitions because `console` is not part of `lib.core.d.ts` or `node.d.ts`.

**Comment by blakeembrey** [comment]
```
typings/main/ambient/node/index.d.ts(329,22): error TS2304: Cannot find name 'Intl'.
typings/main/ambient/node/index.d.ts(355,25): error TS2304: Cannot find name 'console'.
```

**Comment by louy** [comment]
I'm curious, but if `console` is a variable that might be declared in `lib.d.ts` wouldn't redeclaring it in `node.d.ts` cause duplicate declaration error and break for all users not using `lib.core.d.ts`?

**Comment by blakeembrey** [comment]
@louy It shouldn't if the signatures are compatible, but we can check.

**Comment by louy** [comment]
I've just tried adding `message` attribute to `Error` interface and it gave me an error. (I wanted to add a jsdoc comment)

> node_modules/typescript/lib/lib.d.ts(880,5): error TS2300: Duplicate identifier 'message'.
> 4/node.d.ts(22,3): error TS2300: Duplicate identifier 'message'.

So I guess this won't work.

**Comment by blakeembrey** [comment]
Hmm, I'll give it a shot too. Let me try, because they are technically different on node and browsers so it'd be good to type it correctly (and make it work if users are using the default browser typings).

**Comment by louy** [comment]
I think it would be nice if we have a separate version with `noLib` support. Let me know once you've tried that.

**Comment by blakeembrey** [comment]
@louy Sorry for the delay, I just confirmed it works perfectly fine (interfaces merge properly). The only issue I haven't resolved is `new console.Console(process.stdout)` that node allows.

**Comment by blakeembrey** [comment]
@louy Actually, got it, easy. Just do:

```ts
declare interface Console {
  log (msg: any, ...params: any[]): void;
  info (msg: any, ...params: any[]): void;
  warn (msg: any, ...params: any[]): void;
  error (msg: any, ...params: any[]): void;
  dir (value: any, ...params: any[]): void;
  time (timerName?: string): void;
  timeEnd (timerName?: string): void;
  trace (msg: any, ...params: any[]): void;
  assert (test?: boolean, msg?: string, ...params: any[]): void;

  Console: new (stdout: any /* Change this to write-able stream */) => Console;
}

declare var console: Console;
```

**Comment by louy** [comment]
Really? can you put it in a branch?
